### ISSUE TITLE
Ambigious include

### ISSUE THREAD

**Issue by martinixs** [theblacksmith/yii-boilerplate#1]
\yii-boilerplate\protected\extensions\yiihppie\vendors\HamlPHP\src\HamlPHP\HamlPHP.php contains ambigious include

```
require_once 'Config.php';
```

It includes Config.php from Pear directory on my installation. I've managed to solve the issue by rewriting it as

```
require_once dirname(__FILE__) . '/Config.php';
```

**Comment by svallory** [comment]
Fixed in HamlPHP
